name: sdf-install
description: Run common installation steps for a NetSuite SDF Project
runs:
  using: 'composite'

  steps:
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/18'
    
    - name: Install JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
